"$schema" = 'https://starship.rs/config-schema.json'

## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░

# Setups
format="$directory$git_branch$character"
right_format = """$git_status$cmd_duration"""
palette = "matugen"
add_newline = false 

# Other languages configurations:
c.disabled = true
cmake.disabled = true
haskell.disabled = true
python.disabled = true
ruby.disabled = true
rust.disabled = true
perl.disabled = true
package.disabled = true
lua.disabled = true
nodejs.disabled = true
java.disabled = true
golang.disabled = true

[conda]
format = ' [$symbol$environment](color2) '

[character]
success_symbol = "[](primary bold)"
error_symbol = "[](error)"
vimcmd_symbol = "[](color2)"

[directory]
format = "[]($style)[ ](bg:primary_container fg:on_primary_container)[$path](bg:primary_container fg:on_primary_container bold)[ ]($style)"
style = "bg:none fg:primary_container"
truncation_length = 3
truncate_to_repo=false

[git_branch]
format = "[]($style)[[ ](bg:secondary_container fg:on_secondary_container bold)$branch](bg:secondary_container fg:on_secondary_container)[ ]($style)"
style = "bg:none fg:secondary_container"

[git_status]
# $all status$ahead_behind
format = "[]($style)[$all_status$ahead_behind](bg:secondary_container fg:on_secondary_container)[ ]($style)"
style = "bg:none fg:secondary_container"
conflicted = ""
ahead =	"⇡"
behind = "⇣"
diverged = "⇡⇣"
up_to_date = "󰚰"
untracked = " "
stashed = "󰴮 "
modified = " "
staged = " "
renamed = " "
deleted = " "

[cmd_duration]
min_time = 1
# duration & style 
format = "[]($style)[[󰥔 ](bg:tertiary_container fg:on_tertiary_container bold)$duration](bg:tertiary_container fg:on_tertiary_container)[ ]($style)"
disabled = false
style = "bg:none fg:tertiary_container"

[palettes.matugen]

background = "#101418"

color1 = "#ffb1c6"

color10 = "#a1d399"

color10_container = "#245023"

color10_source = "#c3e88d"

color10_value = "#c3e88d"

color11 = "#e4c36c"

color11_container = "#594400"

color11_source = "#ffc777"

color11_value = "#ffc777"

color12 = "#a4c9fe"

color12_container = "#1f4876"

color12_source = "#82aaff"

color12_value = "#82aaff"

color13 = "#c6c0ff"

color13_container = "#454078"

color13_source = "#c099ff"

color13_value = "#c099ff"

color14 = "#8fcff3"

color14_container = "#004c68"

color14_source = "#86e1fc"

color14_value = "#86e1fc"

color1_container = "#703347"

color1_source = "#ff757f"

color1_value = "#ff757f"

color2 = "#a1d399"

color2_container = "#245023"

color2_source = "#c3e88d"

color2_value = "#c3e88d"

color3 = "#e4c36c"

color3_container = "#594400"

color3_source = "#ffc777"

color3_value = "#ffc777"

color4 = "#a4c9fe"

color4_container = "#1f4876"

color4_source = "#82aaff"

color4_value = "#82aaff"

color5 = "#c6c0ff"

color5_container = "#454078"

color5_source = "#c099ff"

color5_value = "#c099ff"

color6 = "#8fcff3"

color6_container = "#004c68"

color6_source = "#86e1fc"

color6_value = "#86e1fc"

color9 = "#ffb1c6"

color9_container = "#703347"

color9_source = "#ff757f"

color9_value = "#ff757f"

error = "#ffb4ab"

error_container = "#93000a"

inverse_on_surface = "#2d3135"

inverse_primary = "#2f628c"

inverse_surface = "#e0e2e8"

on_background = "#e0e2e8"

on_color1 = "#551d31"

on_color10 = "#0b390f"

on_color10_container = "#bdf0b3"

on_color11 = "#3d2e00"

on_color11_container = "#ffdf91"

on_color12 = "#00315c"

on_color12_container = "#d3e3ff"

on_color13 = "#2e295f"

on_color13_container = "#e4dfff"

on_color14 = "#003549"

on_color14_container = "#c3e8ff"

on_color1_container = "#ffd9e1"

on_color2 = "#0b390f"

on_color2_container = "#bdf0b3"

on_color3 = "#3d2e00"

on_color3_container = "#ffdf91"

on_color4 = "#00315c"

on_color4_container = "#d3e3ff"

on_color5 = "#2e295f"

on_color5_container = "#e4dfff"

on_color6 = "#003549"

on_color6_container = "#c3e8ff"

on_color9 = "#551d31"

on_color9_container = "#ffd9e1"

on_error = "#690005"

on_error_container = "#ffdad6"

on_primary = "#003353"

on_primary_container = "#cee5ff"

on_primary_fixed = "#001d33"

on_primary_fixed_variant = "#0f4a73"

on_secondary = "#243240"

on_secondary_container = "#d5e4f7"

on_secondary_fixed = "#0e1d2a"

on_secondary_fixed_variant = "#3a4857"

on_surface = "#e0e2e8"

on_surface_variant = "#c2c7cf"

on_tertiary = "#392a49"

on_tertiary_container = "#efdbff"

on_tertiary_fixed = "#231533"

on_tertiary_fixed_variant = "#504061"

outline = "#8c9198"

outline_variant = "#42474e"

primary = "#9bcbfb"

primary_container = "#0f4a73"

primary_fixed = "#cee5ff"

primary_fixed_dim = "#9bcbfb"

scrim = "#000000"

secondary = "#b9c8da"

secondary_container = "#3a4857"

secondary_fixed = "#d5e4f7"

secondary_fixed_dim = "#b9c8da"

shadow = "#000000"

source_color = "#486b8c"

surface = "#101418"

surface_bright = "#36393e"

surface_container = "#1c2024"

surface_container_high = "#272a2f"

surface_container_highest = "#323539"

surface_container_low = "#181c20"

surface_container_lowest = "#0b0f12"

surface_dim = "#101418"

surface_variant = "#42474e"

tertiary = "#d3bfe6"

tertiary_container = "#504061"

tertiary_fixed = "#efdbff"

tertiary_fixed_dim = "#d3bfe6"

