"$schema" = 'https://starship.rs/config-schema.json'

## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░

# Setups
format="$directory$git_branch$character"
right_format = """$git_status$cmd_duration"""
palette = "matugen"
add_newline = false 

# Other languages configurations:
c.disabled = true
cmake.disabled = true
haskell.disabled = true
python.disabled = true
ruby.disabled = true
rust.disabled = true
perl.disabled = true
package.disabled = true
lua.disabled = true
nodejs.disabled = true
java.disabled = true
golang.disabled = true

[conda]
format = ' [$symbol$environment](color2) '

[character]
success_symbol = "[](primary bold)"
error_symbol = "[](error)"
vimcmd_symbol = "[](color2)"

[directory]
format = "[]($style)[ ](bg:primary_container fg:on_primary_container)[$path](bg:primary_container fg:on_primary_container bold)[ ]($style)"
style = "bg:none fg:primary_container"
truncation_length = 3
truncate_to_repo=false

[git_branch]
format = "[]($style)[[ ](bg:secondary_container fg:on_secondary_container bold)$branch](bg:secondary_container fg:on_secondary_container)[ ]($style)"
style = "bg:none fg:secondary_container"

[git_status]
# $all status$ahead_behind
format = "[]($style)[$all_status$ahead_behind](bg:secondary_container fg:on_secondary_container)[ ]($style)"
style = "bg:none fg:secondary_container"
conflicted = "="
ahead =	"⇡"
behind = "⇣"
diverged = "⇡⇣"
up_to_date = ""
untracked = "?"
stashed = "\\$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

[cmd_duration]
min_time = 1
# duration & style 
format = "[]($style)[[󰥔 ](bg:tertiary_container fg:on_tertiary_container bold)$duration](bg:tertiary_container fg:on_tertiary_container)[ ]($style)"
disabled = false
style = "bg:none fg:tertiary_container"

[palettes.matugen]

background = "#111318"

color1 = "#ffb1c6"

color10 = "#a1d399"

color10_container = "#245023"

color10_source = "#c3e88d"

color10_value = "#c3e88d"

color11 = "#ffb779"

color11_container = "#6b3b04"

color11_source = "#ffc777"

color11_value = "#ffc777"

color12 = "#adc6ff"

color12_container = "#2a4678"

color12_source = "#82aaff"

color12_value = "#82aaff"

color13 = "#c6c0ff"

color13_container = "#454078"

color13_source = "#c099ff"

color13_value = "#c099ff"

color14 = "#8fcef3"

color14_container = "#004c68"

color14_source = "#86e1fc"

color14_value = "#86e1fc"

color1_container = "#703347"

color1_source = "#ff757f"

color1_value = "#ff757f"

color2 = "#a1d399"

color2_container = "#245023"

color2_source = "#c3e88d"

color2_value = "#c3e88d"

color3 = "#ffb779"

color3_container = "#6b3b04"

color3_source = "#ffc777"

color3_value = "#ffc777"

color4 = "#adc6ff"

color4_container = "#2a4678"

color4_source = "#82aaff"

color4_value = "#82aaff"

color5 = "#c6c0ff"

color5_container = "#454078"

color5_source = "#c099ff"

color5_value = "#c099ff"

color6 = "#8fcef3"

color6_container = "#004c68"

color6_source = "#86e1fc"

color6_value = "#86e1fc"

color9 = "#ffb1c6"

color9_container = "#703347"

color9_source = "#ff757f"

color9_value = "#ff757f"

error = "#ffb4ab"

error_container = "#93000a"

inverse_on_surface = "#2e3036"

inverse_primary = "#425e91"

inverse_surface = "#e2e2e9"

on_background = "#e2e2e9"

on_color1 = "#551d31"

on_color10 = "#0b390f"

on_color10_container = "#bdf0b3"

on_color11 = "#4c2700"

on_color11_container = "#ffdcc1"

on_color12 = "#0f2f60"

on_color12_container = "#d8e2ff"

on_color13 = "#2e295f"

on_color13_container = "#e4dfff"

on_color14 = "#003549"

on_color14_container = "#c3e8ff"

on_color1_container = "#ffd9e1"

on_color2 = "#0b390f"

on_color2_container = "#bdf0b3"

on_color3 = "#4c2700"

on_color3_container = "#ffdcc1"

on_color4 = "#0f2f60"

on_color4_container = "#d8e2ff"

on_color5 = "#2e295f"

on_color5_container = "#e4dfff"

on_color6 = "#003549"

on_color6_container = "#c3e8ff"

on_color9 = "#551d31"

on_color9_container = "#ffd9e1"

on_error = "#690005"

on_error_container = "#ffdad6"

on_primary = "#0d2f5f"

on_primary_container = "#d7e2ff"

on_primary_fixed = "#001b3f"

on_primary_fixed_variant = "#294677"

on_secondary = "#283041"

on_secondary_container = "#dae2f9"

on_secondary_fixed = "#131c2c"

on_secondary_fixed_variant = "#3f4759"

on_surface = "#e2e2e9"

on_surface_variant = "#c4c6d0"

on_tertiary = "#3f2844"

on_tertiary_container = "#fad7fc"

on_tertiary_fixed = "#29132e"

on_tertiary_fixed_variant = "#573e5b"

outline = "#8e9099"

outline_variant = "#44474e"

primary = "#abc7ff"

primary_container = "#294677"

primary_fixed = "#d7e2ff"

primary_fixed_dim = "#abc7ff"

scrim = "#000000"

secondary = "#bec6dc"

secondary_container = "#3f4759"

secondary_fixed = "#dae2f9"

secondary_fixed_dim = "#bec6dc"

shadow = "#000000"

source_color = "#2c323f"

surface = "#111318"

surface_bright = "#37393e"

surface_container = "#1e2025"

surface_container_high = "#282a2f"

surface_container_highest = "#33353a"

surface_container_low = "#1a1c20"

surface_container_lowest = "#0c0e13"

surface_dim = "#111318"

surface_variant = "#44474e"

tertiary = "#ddbce0"

tertiary_container = "#573e5b"

tertiary_fixed = "#fad7fc"

tertiary_fixed_dim = "#ddbce0"

