"$schema" = 'https://starship.rs/config-schema.json'

## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░

# Setups
format="$directory$git_branch$character"
right_format = """$git_status$cmd_duration"""
palette = "matugen"
add_newline = false 

# Other languages configurations:
c.disabled = true
cmake.disabled = true
haskell.disabled = true
python.disabled = true
ruby.disabled = true
rust.disabled = true
perl.disabled = true
package.disabled = true
lua.disabled = true
nodejs.disabled = true
java.disabled = true
golang.disabled = true

[conda]
format = ' [$symbol$environment](color2) '

[character]
success_symbol = "[](primary bold)"
error_symbol = "[](error)"
vimcmd_symbol = "[](color2)"

[directory]
format = "[]($style)[ ](bg:primary_container fg:on_primary_container)[$path](bg:primary_container fg:on_primary_container bold)[ ]($style)"
style = "bg:none fg:primary_container"
truncation_length = 3
truncate_to_repo=false

[git_branch]
format = "[]($style)[[ ](bg:secondary_container fg:on_secondary_container bold)$branch](bg:secondary_container fg:on_secondary_container)[ ]($style)"
style = "bg:none fg:secondary_container"

[git_status]
# $all status$ahead_behind
format = "[]($style)[$all_status$ahead_behind](bg:secondary_container fg:on_secondary_container)[ ]($style)"
style = "bg:none fg:secondary_container"
conflicted = ""
ahead =	"⇡"
behind = "⇣"
diverged = "⇡⇣"
up_to_date = "󰚰"
untracked = " "
stashed = "󰴮 "
modified = " "
staged = " "
renamed = " "
deleted = " "

[cmd_duration]
min_time = 1
# duration & style 
format = "[]($style)[[󰥔 ](bg:tertiary_container fg:on_tertiary_container bold)$duration](bg:tertiary_container fg:on_tertiary_container)[ ]($style)"
disabled = false
style = "bg:none fg:tertiary_container"

[palettes.matugen]

background = "#101510"

color1 = "#ffb4a3"

color10 = "#a3d397"

color10_container = "#275022"

color10_source = "#c3e88d"

color10_value = "#c3e88d"

color11 = "#e4c36c"

color11_container = "#594400"

color11_source = "#ffc777"

color11_value = "#ffc777"

color12 = "#81d3de"

color12_container = "#004f56"

color12_source = "#b2ccd6"

color12_value = "#b2ccd6"

color13 = "#e3b7f3"

color13_container = "#5c396c"

color13_source = "#bb80b3"

color13_value = "#bb80b3"

color14 = "#80d4db"

color14_container = "#004f54"

color14_source = "#86e1fc"

color14_value = "#86e1fc"

color1_container = "#723426"

color1_source = "#f07178"

color1_value = "#f07178"

color2 = "#a3d397"

color2_container = "#275022"

color2_source = "#c3e88d"

color2_value = "#c3e88d"

color3 = "#ffb68a"

color3_container = "#6f3811"

color3_source = "#f78c6c"

color3_value = "#f78c6c"

color4 = "#9ecafc"

color4_container = "#164974"

color4_source = "#82aaff"

color4_value = "#82aaff"

color5 = "#d0bcfe"

color5_container = "#4d3d75"

color5_source = "#c792ea"

color5_value = "#c792ea"

color6 = "#82d3e1"

color6_container = "#004f58"

color6_source = "#89ddff"

color6_value = "#89ddff"

color9 = "#ffb4a4"

color9_container = "#733427"

color9_source = "#ff757f"

color9_value = "#ff757f"

error = "#ffb4ab"

error_container = "#93000a"

inverse_on_surface = "#2c322d"

inverse_primary = "#2d6a44"

inverse_surface = "#dfe4dd"

on_background = "#dfe4dd"

on_color1 = "#561f12"

on_color10 = "#0f380d"

on_color10_container = "#bff0b1"

on_color11 = "#3d2e00"

on_color11_container = "#ffdf91"

on_color12 = "#00363c"

on_color12_container = "#9df0fb"

on_color13 = "#442254"

on_color13_container = "#f7d8ff"

on_color14 = "#00363a"

on_color14_container = "#9df0f8"

on_color1_container = "#ffdad2"

on_color2 = "#0f380d"

on_color2_container = "#bff0b1"

on_color3 = "#522300"

on_color3_container = "#ffdbc8"

on_color4 = "#003256"

on_color4_container = "#d0e4ff"

on_color5 = "#36265d"

on_color5_container = "#e9ddff"

on_color6 = "#00363d"

on_color6_container = "#9eeffe"

on_color9 = "#561f13"

on_color9_container = "#ffdad3"

on_error = "#690005"

on_error_container = "#ffdad6"

on_primary = "#00391d"

on_primary_container = "#b1f1c2"

on_primary_fixed = "#00210e"

on_primary_fixed_variant = "#11512e"

on_secondary = "#223527"

on_secondary_container = "#d2e8d4"

on_secondary_fixed = "#0d1f13"

on_secondary_fixed_variant = "#384b3c"

on_surface = "#dfe4dd"

on_surface_variant = "#c0c9bf"

on_tertiary = "#023640"

on_tertiary_container = "#beeaf7"

on_tertiary_fixed = "#001f26"

on_tertiary_fixed_variant = "#214c57"

outline = "#8b938a"

outline_variant = "#414942"

primary = "#95d5a7"

primary_container = "#11512e"

primary_fixed = "#b1f1c2"

primary_fixed_dim = "#95d5a7"

scrim = "#000000"

secondary = "#b6ccb9"

secondary_container = "#384b3c"

secondary_fixed = "#d2e8d4"

secondary_fixed_dim = "#b6ccb9"

shadow = "#000000"

source_color = "#1d5b37"

surface = "#101510"

surface_bright = "#353a36"

surface_container = "#1c211c"

surface_container_high = "#262b27"

surface_container_highest = "#313631"

surface_container_low = "#181d18"

surface_container_lowest = "#0a0f0b"

surface_dim = "#101510"

surface_variant = "#414942"

tertiary = "#a2cdda"

tertiary_container = "#214c57"

tertiary_fixed = "#beeaf7"

tertiary_fixed_dim = "#a2cdda"

