"$schema" = 'https://starship.rs/config-schema.json'

format = """
\
[](mauve)\
$os\
$username\
[](bg:pink fg:mauve)\
$directory\
[](fg:pink bg:lavender)\
$git_branch\
$git_status\
$character
"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "bg:mauve fg:base"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:mauve fg:mantle"
style_root = "bg:mauve fg:mantle"
format = '[ $user ]($style)'

[directory]
style = "fg:mantle bg:pink"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:lavender"
format = '[[ $symbol $branch ](fg:mantle bg:lavender)]($style)'

[git_status]
style = "bg:lavender"
format = '[[($all_status$ahead_behind )](fg:mantle bg:lavender)]($style)'

[nodejs]
symbol = ""
style = "bg:flamingo"
format = '[[ $symbol( $version) ](fg:mantle bg:flamingo)]($style)'

[c]
symbol = " "
style = "bg:flamingo"
format = '[[ $symbol( $version) ](fg:mantle bg:flamingo)]($style)'

[rust]
symbol = ""
style = "bg:flamingo"
format = '[[ $symbol( $version) ](fg:mantle bg:flamingo)]($style)'

[golang]
symbol = ""
style = "bg:flamingo"
format = '[[ $symbol( $version) ](fg:mantle bg:flamingo)]($style)'

[php]
symbol = ""
style = "bg:flamingo"
format = '[[ $symbol( $version) ](fg:mantle bg:flamingo)]($style)'

[java]
symbol = " "
style = "bg:flamingo"
format = '[[ $symbol( $version) ](fg:mantle bg:flamingo)]($style)'

[kotlin]
symbol = ""
style = "bg:flamingo"
format = '[[ $symbol( $version) ](fg:mantle bg:flamingo)]($style)'

[haskell]
symbol = ""
style = "bg:flamingo"
format = '[[ $symbol( $version) ](fg:mantle bg:flamingo)]($style)'

[python]
symbol = ""
style = "bg:flamingo"
format = '[[ $symbol( $version) ](fg:mantle bg:flamingo)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:surface0"
format = '[[  $time ](fg:text bg:surface0)]($style)'

[line_break]
disabled = false

[character]
disabled = false
format = '$symbol '
# success_symbol = '[I](bold fg:green)'
# error_symbol = '[I](bold fg:green)'
# vimcmd_symbol = '[N](bold fg:blue)'
# vimcmd_replace_one_symbol = '[r](bold fg:red)'
# vimcmd_replace_symbol = '[R](bold fg:red)'
# vimcmd_visual_symbol= '[V](bold fg:mauve)'
success_symbol = '[](bg:teal fg:lavender)[  I](bg:teal fg:base)[](fg:teal)'
error_symbol = '[](bg:teal fg:lavender)[  I](bg:teal fg:base)[](fg:teal)'
vimcmd_symbol = '[](bg:blue fg:lavender)[  N](bg:blue fg:base)[](fg:blue)'
vimcmd_replace_one_symbol = '[](bg:red fg:lavender)[  r](bg:red fg:base)[](fg:red)'
vimcmd_replace_symbol = '[](bg:red fg:lavender)[  R](bg:red fg:base)[](fg:red)'
vimcmd_visual_symbol = '[](bg:mauve fg:lavender)[  V](bg:mauve fg:base)[](fg:mauve)'

