"$schema" = 'https://starship.rs/config-schema.json'

## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░

# Setups
format="$directory$git_branch$character"
right_format = """$git_status$cmd_duration"""
palette = "matugen"
add_newline = false 

# Other languages configurations:
c.disabled = true
cmake.disabled = true
haskell.disabled = true
python.disabled = true
ruby.disabled = true
rust.disabled = true
perl.disabled = true
package.disabled = true
lua.disabled = true
nodejs.disabled = true
java.disabled = true
golang.disabled = true

[conda]
format = ' [$symbol$environment](color2) '

[character]
success_symbol = "[](primary bold)"
error_symbol = "[](error)"
vimcmd_symbol = "[](color2)"

[directory]
format = "[]($style)[ ](bg:primary_container fg:on_primary_container)[$path](bg:primary_container fg:on_primary_container bold)[ ]($style)"
style = "bg:none fg:primary_container"
truncation_length = 3
truncate_to_repo=false

[git_branch]
format = "[]($style)[[ ](bg:secondary_container fg:on_secondary_container bold)$branch](bg:secondary_container fg:on_secondary_container)[ ]($style)"
style = "bg:none fg:secondary_container"

[git_status]
# $all status$ahead_behind
format = "[]($style)[$all_status$ahead_behind](bg:secondary_container fg:on_secondary_container)[ ]($style)"
style = "bg:none fg:secondary_container"
conflicted = ""
ahead =	"⇡"
behind = "⇣"
diverged = "⇡⇣"
up_to_date = "󰚰"
untracked = " "
stashed = "󰴮 "
modified = " "
staged = " "
renamed = " "
deleted = " "

[cmd_duration]
min_time = 1
# duration & style 
format = "[]($style)[[󰥔 ](bg:tertiary_container fg:on_tertiary_container bold)$duration](bg:tertiary_container fg:on_tertiary_container)[ ]($style)"
disabled = false
style = "bg:none fg:tertiary_container"

[palettes.matugen]

background = "#0f1417"

color1 = "#ffb1c5"

color10 = "#a1d399"

color10_container = "#245023"

color10_source = "#c3e88d"

color10_value = "#c3e88d"

color11 = "#e4c36c"

color11_container = "#594400"

color11_source = "#ffc777"

color11_value = "#ffc777"

color12 = "#89d0ed"

color12_container = "#004d62"

color12_source = "#b2ccd6"

color12_value = "#b2ccd6"

color13 = "#e3b7f3"

color13_container = "#5c396c"

color13_source = "#bb80b3"

color13_value = "#bb80b3"

color14 = "#89d0ed"

color14_container = "#004d62"

color14_source = "#86e1fc"

color14_value = "#86e1fc"

color1_container = "#703346"

color1_source = "#f07178"

color1_value = "#f07178"

color2 = "#a1d399"

color2_container = "#245023"

color2_source = "#c3e88d"

color2_value = "#c3e88d"

color3 = "#ffb3b1"

color3_container = "#733333"

color3_source = "#f78c6c"

color3_value = "#f78c6c"

color4 = "#9ecafc"

color4_container = "#164974"

color4_source = "#82aaff"

color4_value = "#82aaff"

color5 = "#d0bcfe"

color5_container = "#4d3d75"

color5_source = "#c792ea"

color5_value = "#c792ea"

color6 = "#8bd0f0"

color6_container = "#004d64"

color6_source = "#89ddff"

color6_value = "#89ddff"

color9 = "#ffb1c6"

color9_container = "#703347"

color9_source = "#ff757f"

color9_value = "#ff757f"

error = "#ffb4ab"

error_container = "#93000a"

inverse_on_surface = "#2c3134"

inverse_primary = "#196584"

inverse_surface = "#dfe3e7"

on_background = "#dfe3e7"

on_color1 = "#551d30"

on_color10 = "#0b390f"

on_color10_container = "#bdf0b3"

on_color11 = "#3d2e00"

on_color11_container = "#ffdf91"

on_color12 = "#003545"

on_color12_container = "#baeaff"

on_color13 = "#442254"

on_color13_container = "#f7d8ff"

on_color14 = "#003545"

on_color14_container = "#baeaff"

on_color1_container = "#ffd9e1"

on_color2 = "#0b390f"

on_color2_container = "#bdf0b3"

on_color3 = "#571d1f"

on_color3_container = "#ffdad8"

on_color4 = "#003256"

on_color4_container = "#d0e4ff"

on_color5 = "#36265d"

on_color5_container = "#e9ddff"

on_color6 = "#003546"

on_color6_container = "#bee9ff"

on_color9 = "#551d31"

on_color9_container = "#ffd9e1"

on_error = "#690005"

on_error_container = "#ffdad6"

on_primary = "#003548"

on_primary_container = "#c1e8ff"

on_primary_fixed = "#001e2b"

on_primary_fixed_variant = "#004d67"

on_secondary = "#1f333d"

on_secondary_container = "#d1e6f3"

on_secondary_fixed = "#091e28"

on_secondary_fixed_variant = "#364954"

on_surface = "#dfe3e7"

on_surface_variant = "#c0c7cd"

on_tertiary = "#312c4c"

on_tertiary_container = "#e5deff"

on_tertiary_fixed = "#1b1736"

on_tertiary_fixed_variant = "#474364"

outline = "#8a9297"

outline_variant = "#40484d"

primary = "#8ecff2"

primary_container = "#004d67"

primary_fixed = "#c1e8ff"

primary_fixed_dim = "#8ecff2"

scrim = "#000000"

secondary = "#b5c9d7"

secondary_container = "#364954"

secondary_fixed = "#d1e6f3"

secondary_fixed_dim = "#b5c9d7"

shadow = "#000000"

source_color = "#d1dce4"

surface = "#0f1417"

surface_bright = "#353a3d"

surface_container = "#1b2023"

surface_container_high = "#262b2e"

surface_container_highest = "#313539"

surface_container_low = "#171c1f"

surface_container_lowest = "#0a0f12"

surface_dim = "#0f1417"

surface_variant = "#40484d"

tertiary = "#c9c2ea"

tertiary_container = "#474364"

tertiary_fixed = "#e5deff"

tertiary_fixed_dim = "#c9c2ea"

