import = [
    "~/.cache/wal/colors-alacritty-term-only.toml"
]

[env]
TERM="alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[window]
decorations = "None"

# [colors]
# transparent_background_colors = true
