[general]
background = "{{colors.surface.default.hex}}"
border = "{{colors.outline.default.hex}}"
horizontal_rule = "{{colors.outline.default.hex}}"
unread_indicator = "{{colors.primary.default.hex}}"

[text]
primary = "{{colors.on_surface.default.hex}}"
secondary = "{{colors.on_surface.default.hex}}"
tertiary = "{{colors.on_surface.default.hex}}"
success = "{{colors.tertiary.default.hex}}"
error = "{{colors.error.default.hex}}"

[buttons.primary]
background = "{{colors.surface_container.default.hex}}"
background_hover = "{{colors.surface_container_high.default.hex}}"
background_selected = "{{colors.surface_container_high.default.hex}}"
background_selected_hover = "{{colors.surface_container_highest.default.hex}}"

[buttons.secondary]
background = "{{colors.surface_container.default.hex}}"
background_hover = "{{colors.surface_container_high.default.hex}}"
background_selected = "{{colors.surface_container_high.default.hex}}"
background_selected_hover = "{{colors.surface_container_highest.default.hex}}"

[buffer]
action = "{{colors.primary.default.hex}}"
background = "{{colors.surface_container.default.hex}}"
background_text_input = "{{colors.surface_container_high.default.hex}}"
background_title_bar = "{{colors.surface_container_high.default.hex}}"
border = "{{colors.outline_variant.default.hex}}"
border_selected = "{{colors.outline.default.hex}}"
code = "{{colors.surface_container_high.default.hex}}"
highlight = "{{colors.tertiary.default.hex}}"
nickname = "{{colors.secondary.default.hex}}"
selection = "{{colors.primary.default.hex}}"
timestamp = "{{colors.on_surface_variant.default.hex}}"
topic = "{{colors.on_surface_variant.default.hex}}"
url = "{{colors.primary.default.hex}}"

[buffer.server_messages]
# Set below if you want to have a unique color for each.
# Otherwise simply set `default` to use that for all server messages.
#
# change_host = "<string>"
# join = "<string>"
# part = "<string>"
# quit = "<string>"
# reply_topic = "<string>"
# monitored_online = "<string>"
# monitored_offline = "<string>"
default = "{{colors.tertiary.default.hex}}"
