"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](mauve)\
$os\
$username\
[](bg:lavender fg:mauve)\
$directory\
[](fg:lavender bg:pink)\
$git_branch\
$git_status\
[](fg:pink) \ 
"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "bg:mauve fg:base"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:mauve fg:mantle"
style_root = "bg:mauve fg:mantle"
format = '[ $user ]($style)'

[directory]
style = "fg:mantle bg:lavender"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:pink"
format = '[[ $symbol $branch ](fg:mantle bg:pink)]($style)'

[git_status]
style = "bg:pink"
format = '[[($all_status$ahead_behind )](fg:mantle bg:pink)]($style)'

[nodejs]
symbol = ""
style = "bg:flamingo"
format = '[[ $symbol( $version) ](fg:mantle bg:flamingo)]($style)'

[c]
symbol = " "
style = "bg:flamingo"
format = '[[ $symbol( $version) ](fg:mantle bg:flamingo)]($style)'

[rust]
symbol = ""
style = "bg:flamingo"
format = '[[ $symbol( $version) ](fg:mantle bg:flamingo)]($style)'

[golang]
symbol = ""
style = "bg:flamingo"
format = '[[ $symbol( $version) ](fg:mantle bg:flamingo)]($style)'

[php]
symbol = ""
style = "bg:flamingo"
format = '[[ $symbol( $version) ](fg:mantle bg:flamingo)]($style)'

[java]
symbol = " "
style = "bg:flamingo"
format = '[[ $symbol( $version) ](fg:mantle bg:flamingo)]($style)'

[kotlin]
symbol = ""
style = "bg:flamingo"
format = '[[ $symbol( $version) ](fg:mantle bg:flamingo)]($style)'

[haskell]
symbol = ""
style = "bg:flamingo"
format = '[[ $symbol( $version) ](fg:mantle bg:flamingo)]($style)'

[python]
symbol = ""
style = "bg:flamingo"
format = '[[ $symbol( $version) ](fg:mantle bg:flamingo)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:surface0"
format = '[[  $time ](fg:text bg:surface0)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:mauve)'
vimcmd_replace_symbol = '[](bold fg:mauve)'
vimcmd_visual_symbol = '[](bold fg:yellow)'

