[window]
opacity = {background.alpha_dec}

[colors.primary]
background = "{background}"
foreground = "{foreground}"

[colors.cursor]
text = "{background}"
cursor = "{foreground}"

[colors.vi_mode_cursor]
text = "{background}"
cursor = "{foreground}"

[colors.search.matches]
foreground = "{color0}"
background = "{color15}"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "{color8}"
background = "{color7}"

[colors.selection]
text = "CellBackground"
background = "CellForeground"
