[window]
opacity = {{custom.alpha}}

[colors.primary]
background = "{{colors.background.default.hex}}"
foreground = "{{colors.on_background.default.hex}}"

[colors.search.matches]
foreground = '{{colors.on_primary_container.default.hex}}'
background = '{{colors.primary_container.default.hex}}'

[colors.search.focused_match]
foreground = '{{colors.on_secondary_container.default.hex}}'
background = '{{colors.secondary_container.default.hex}}'

[colors.footer_bar]
foreground = '{{colors.on_surface_variant.default.hex}}'
background = '{{colors.surface_container.default.hex}}'

[colors.hints.start]
foreground = '{{colors.on_surface_variant.default.hex}}'
background = '{{colors.surface_container.default.hex}}'

[colors.hints.end]
foreground = '{{colors.on_surface_variant.default.hex}}'
background = '{{colors.surface_container.default.hex}}'

[colors.selection]
text = '{{colors.inverse_on_surface.default.hex}}'
background = '{{colors.inverse_surface.default.hex}}'

[colors.normal]
black = "{{colors.surface_container.default.hex}}"
red = "{{colors.color1.default.hex}}"
green = "{{colors.color2.default.hex}}"
yellow = "{{colors.color3.default.hex}}"
blue = "{{colors.color4.default.hex}}"
magenta = "{{colors.color5.default.hex}}"
cyan = "{{colors.color6.default.hex}}"
white = "{{colors.on_surface_variant.default.hex}}"

[colors.bright]
black = "{{colors.surface_container_high.default.hex}}"
red = "{{colors.color9.default.hex}}"
green = "{{colors.color10.default.hex}}"
yellow = "{{colors.color11.default.hex}}"
blue = "{{colors.color12.default.hex}}"
magenta = "{{colors.color13.default.hex}}"
cyan = "{{colors.color14.default.hex}}"
white = "{{colors.on_surface.default.hex}}"

[colors.dim]
black = "{{colors.surface_container.default.hex}}"
red = "{{colors.color1.default.hex}}"
green = "{{colors.color2.default.hex}}"
yellow = "{{colors.color3.default.hex}}"
blue = "{{colors.color4.default.hex}}"
magenta = "{{colors.color5.default.hex}}"
cyan = "{{colors.color6.default.hex}}"
white = "{{colors.on_surface_variant.default.hex}}"
