[window]
opacity = 0.7

[colors.primary]
background = "#0f1417"
foreground = "#dfe3e7"

[colors.search.matches]
foreground = '#c1e8ff'
background = '#004d67'

[colors.search.focused_match]
foreground = '#d1e6f3'
background = '#364954'

[colors.footer_bar]
foreground = '#c0c7cd'
background = '#1b2023'

[colors.hints.start]
foreground = '#c0c7cd'
background = '#1b2023'

[colors.hints.end]
foreground = '#c0c7cd'
background = '#1b2023'

[colors.selection]
text = '#2c3134'
background = '#dfe3e7'

[colors.normal]
black = "#1b2023"
red = "#ffb1c5"
green = "#a1d399"
yellow = "#ffb3b1"
blue = "#9ecafc"
magenta = "#d0bcfe"
cyan = "#8bd0f0"
white = "#c0c7cd"

[colors.bright]
black = "#262b2e"
red = "#ffb1c6"
green = "#a1d399"
yellow = "#e4c36c"
blue = "#89d0ed"
magenta = "#e3b7f3"
cyan = "#89d0ed"
white = "#dfe3e7"

[colors.dim]
black = "#1b2023"
red = "#ffb1c5"
green = "#a1d399"
yellow = "#ffb3b1"
blue = "#9ecafc"
magenta = "#d0bcfe"
cyan = "#8bd0f0"
white = "#c0c7cd"
