[config]
reload_apps = true

[config.custom_keywords]
alpha = "0.84"

[config.custom_colors]
color1 = { color = "#ff757f", blend = true }
color2 = { color = "#c3e88d", blend = true }
color3 = { color = "#ffc777", blend = true }
color4 = { color = "#82aaff", blend = true }
color5 = { color = "#c099ff", blend = true }
color6 = { color = "#86e1fc", blend = true }
color9 = { color = "#ff757f", blend = true }
color10 = { color = "#c3e88d", blend = true }
color11 = { color = "#ffc777", blend = true }
color12 = { color = "#82aaff", blend = true }
color13 = { color = "#c099ff", blend = true }
color14 = { color = "#86e1fc", blend = true }

[config.reload_apps_list]
gtk_theme = true

[templates]
alacritty = { input_path = '~/.config/matugen/templates/alacritty.toml', output_path = '~/.cache/matugen/alacritty.toml' }
foot = { input_path = '~/.config/matugen/templates/foot.ini', output_path = '~/.cache/matugen/foot.ini' }
ags = { input_path = '~/.config/matugen/templates/ags.json', output_path = '~/.cache/matugen/ags.json' }
fish = { input_path = '~/.config/matugen/templates/colors.fish', output_path = '~/.cache/matugen/colors.fish' }
vim = { input_path = '~/.config/matugen/templates/colors.vim', output_path = '~/.cache/matugen/colors.vim' }
gtk-colors = { input_path = '~/.config/matugen/templates/gtk-colors.css', output_path = '~/.cache/matugen/gtk-colors.css' }
qt5-colors = { input_path = '~/.config/matugen/templates/qt5ct-colors.conf', output_path = '~/.config/qt5ct/colors/matugen.conf' }
starship = { input_path = '~/.config/matugen/templates/starship.toml', output_path = '~/.config/starship.toml' }
