[config]
reload_apps = false

[config.custom_keywords]
alpha = "0.78"

[config.custom_colors]
color1 = { color = "#f07178", blend = true }
color2 = { color = "#C3E88D", blend = true }
color3 = { color = "#F78C6C", blend = true }
color4 = { color = "#82AAFF", blend = true }
color5 = { color = "#C792EA", blend = true }
color6 = { color = "#89DDFF", blend = true }
color9 = { color = "#ff757f", blend = true }
color10 = { color = "#c3e88d", blend = true }
color11 = { color = "#ffc777", blend = true }
color12 = { color = "#B2CCD6", blend = true }
color13 = { color = "#bb80b3", blend = true }
color14 = { color = "#86e1fc", blend = true }

[templates]
# terminals
alacritty = { input_path = '~/.config/matugen/templates/terminals/alacritty.toml', output_path = '~/.cache/matugen/alacritty.toml' }
foot = { input_path = '~/.config/matugen/templates/terminals/foot.ini', output_path = '~/.cache/matugen/foot.ini' }

# wezterm
wezterm_colors = { input_path = '~/.config/matugen/templates/wezterm/colors.toml', output_path = '~/.cache/matugen/wezterm/matugen.toml' }
wezterm_config = { input_path = '~/.config/matugen/templates/wezterm/config.lua', output_path = '~/.config/wezterm/extra.lua' }

# desktop
ags = { input_path = '~/.config/matugen/templates/desktop/ags.json', output_path = '~/.cache/matugen/ags.json' }
scss = { input_path = '~/.config/matugen/templates/colors.scss', output_path = '~/.cache/matugen/colors.scss' }
hyprland = { input_path = '~/.config/matugen/templates/desktop/hyprcolors.conf', output_path = '~/.cache/matugen/hyprcolors.conf' }
i3 = { input_path = '~/.config/matugen/templates/desktop/i3', output_path = '~/.cache/matugen/i3' }
gtk-colors = { input_path = '~/.config/matugen/templates/desktop/gtk-colors.css', output_path = '~/.cache/matugen/gtk-colors.css' }
rofi = { input_path = '~/.config/matugen/templates/desktop/rofi.rasi', output_path = '~/.cache/matugen/rofi.rasi' }
qt5-colors = { input_path = '~/.config/matugen/templates/desktop/qt5ct-colors.conf', output_path = '~/.config/qt5ct/colors/matugen.conf' }
qt6-colors = { input_path = '~/.config/matugen/templates/desktop/qt5ct-colors.conf', output_path = '~/.config/qt6ct/colors/matugen.conf' }
glimpse = { input_path = '~/.config/matugen/templates/desktop/glimpse.css', output_path = '~/.config/glimpse/style.css' }

# apps
starship = { input_path = '~/.config/matugen/templates/starship.toml', output_path = '~/.config/starship.toml' }
chromium = { input_path = '~/.config/matugen/templates/chromium.json', output_path = '~/.cache/matugen/chrome/manifest.json' }
discord = { input_path = '~/.config/matugen/templates/discord.css', output_path = '~/.config/vesktop/themes/matugen.css' }
fish = { input_path = '~/.config/matugen/templates/colors.fish', output_path = '~/.cache/matugen/colors.fish' }
vim = { input_path = '~/.config/matugen/templates/colors.vim', output_path = '~/.cache/matugen/colors.vim' }
sh = { input_path = '~/.config/matugen/templates/colors.sh', output_path = '~/.cache/matugen/colors.sh' }
neovim = { input_path = '~/.config/matugen/templates/colors.lua', output_path = '~/.cache/matugen/colors.lua' }
tmux = { input_path = '~/.config/matugen/templates/tmux-colors.conf', output_path = '~/.cache/matugen/tmux.conf' }

# zellij
zellij_layout = { input_path = '~/.config/matugen/templates/zellij/layout.kdl', output_path = '~/.config/zellij/layouts/default.kdl' }
zellij_theme = { input_path = '~/.config/matugen/templates/zellij/theme.kdl', output_path = '~/.config/zellij/themes/default.kdl' }
